/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MyData {
  storyName: string
  storyAuthor: string
  storySource: string
}
export function render(tplPath: string, outPath: string, myData: MyData): void
