/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class DocxTemplate {
  constructor()
  renderFile(tplPath: string, outPath: string, jsonData: string): void
  renderBase64(template: string, jsonData: string): string
  templateMeta(template: string): Array<string>
}
